### ISSUE TITLE
Error in sorting binlogs with `binlog.nnnnnn` filename pattern

### ISSUE THREAD

**Issue by jonhattan** [SHWorX/mysql-binary-logs-analyzer#1]
I get an error when parsing binlogs with `binlog.nnnnnn` filename pattern  (I think it is generated by vanilla redhat mysql 8.x).

Here's the traceback:

```python
Traceback (most recent call last):
  File "/usr/local/bin/analyze-mysqlbinlogs", line 747, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/analyze-mysqlbinlogs", line 742, in main
    run(dtFrom, dtTo, binaryLogsFilePath, binaryLogsFileName, outputPath, sqlOperations)
  File "/usr/local/bin/analyze-mysqlbinlogs", line 646, in run
    binaryLogs = getBinaryLogs(params[0], params[1], params[2], params[3])
  File "/usr/local/bin/analyze-mysqlbinlogs", line 447, in getBinaryLogs
    return sorted(binaryLogs, key=parse)
  File "/home/jonathan/.local/lib/python3.10/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "/home/jonathan/.local/lib/python3.10/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: './binlog.007447'
```

It seems `packaging.version` parser doesn't accept this pattern as a valid version. Just made this change to be able to run the script:

```diff
-return sorted(binaryLogs, key=parse)
+return sorted(binaryLogs)
```

pd. Nice work!

**Comment by CPCoder** [comment]
Thanks for the bug report, I've confirmed it and removed the second argument from the `sorted` method :).
